// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture

RWTexture2D<float4> Result;

StructuredBuffer<float4> Positions;

float4 color;

[numthreads(8,8,1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	// TODO: insert actual code here!
	Result[id.xy] = (id.x & id.y) * color; //Every Pixel

}